module.exports = {
  '&quot;': '"', // 'quotation mark'
  '&apos;': '\'', // 'apostrophe&nbsp'
  '&amp;': '&', // 'ampersand'
  '&lt;': '<', // 'less-than'
  '&gt;': '>', // 'greater-than'
  '&nbsp;': ' ', // 'non-breaking space'
  '&iexcl;': '¡', // 'inverted exclamation mark'
  '&cent;': '¢', // 'cent'
  '&pound;': '£', // 'pound'
  '&curren;': '¤', // 'currency'
  '&yen;': '¥', // 'yen'
  '&brvbar;': '¦', // 'broken vertical bar'
  '&sect;': '§', // 'section'
  '&uml;': '¨', // 'spacing diaeresis'
  '&copy;': '©', // 'copyright'
  '&ordf;': 'ª', // 'feminine ordinal indicator'
  '&laquo;': '«', // 'angle quotation mark (left'
  '&not;': '¬', // 'negation'
  '&reg;': '®', // 'registered trademark'
  '&macr;': '¯', // 'spacing macron'
  '&deg;': '°', // 'degree'
  '&plusmn;': '±', // 'plus-or-minus&nbsp'
  '&sup2;': '²', // 'superscript 2'
  '&sup3;': '³', // 'superscript 3'
  '&acute;': '´', // 'spacing acute'
  '&micro;': 'µ', // 'micro'
  '&para;': '¶', // 'paragraph'
  '&middot;': '·', // 'middle dot'
  '&cedil;': '¸', // 'spacing cedilla'
  '&sup1;': '¹', // 'superscript 1'
  '&ordm;': 'º', // 'masculine ordinal indicator'
  '&raquo;': '»', // 'angle quotation mark (right'
  '&frac14;': '¼', // 'fraction 1/4'
  '&frac12;': '½', // 'fraction 1/2'
  '&frac34;': '¾', // 'fraction 3/4'
  '&iquest;': '¿', // 'inverted question mark'
  '&times;': '×', // 'multiplication'
  '&divide;': '÷', // 'division'
  '&Agrave;': 'À', // 'capital a, grave accent'
  '&Aacute;': 'Á', // 'capital a, acute accent'
  '&Acirc;': 'Â', // 'capital a, circumflex accent'
  '&Atilde;': 'Ã', // 'capital a, tilde'
  '&Auml;': 'Ä', // 'capital a, umlaut mark'
  '&Aring;': 'Å', // 'capital a, ring'
  '&AElig;': 'Æ', // 'capital ae'
  '&Ccedil;': 'Ç', // 'capital c, cedilla'
  '&Egrave;': 'È', // 'capital e, grave accent'
  '&Eacute;': 'É', // 'capital e, acute accent'
  '&Ecirc;': 'Ê', // 'capital e, circumflex accent'
  '&Euml;': 'Ë', // 'capital e, umlaut mark'
  '&Igrave;': 'Ì', // 'capital i, grave accent'
  '&Iacute;': 'Í', // 'capital i, acute accent'
  '&Icirc;': 'Î', // 'capital i, circumflex accent'
  '&Iuml;': 'Ï', // 'capital i, umlaut mark'
  '&ETH;': 'Ð', // 'capital eth, Icelandic'
  '&Ntilde;': 'Ñ', // 'capital n, tilde'
  '&Ograve;': 'Ò', // 'capital o, grave accent'
  '&Oacute;': 'Ó', // 'capital o, acute accent'
  '&Ocirc;': 'Ô', // 'capital o, circumflex accent'
  '&Otilde;': 'Õ', // 'capital o, tilde'
  '&Ouml;': 'Ö', // 'capital o, umlaut mark'
  '&Oslash;': 'Ø', // 'capital o, slash'
  '&Ugrave;': 'Ù', // 'capital u, grave accent'
  '&Uacute;': 'Ú', // 'capital u, acute accent'
  '&Ucirc;': 'Û', // 'capital u, circumflex accent'
  '&Uuml;': 'Ü', // 'capital u, umlaut mark'
  '&Yacute;': 'Ý', // 'capital y, acute accent'
  '&THORN;': 'Þ', // 'capital THORN, Icelandic'
  '&szlig;': 'ß', // 'small sharp s, German'
  '&agrave;': 'à', // 'small a, grave accent'
  '&aacute;': 'á', // 'small a, acute accent'
  '&acirc;': 'â', // 'small a, circumflex accent'
  '&atilde;': 'ã', // 'small a, tilde'
  '&auml;': 'ä', // 'small a, umlaut mark'
  '&aring;': 'å', // 'small a, ring'
  '&aelig;': 'æ', // 'small ae'
  '&ccedil;': 'ç', // 'small c, cedilla'
  '&egrave;': 'è', // 'small e, grave accent'
  '&eacute;': 'é', // 'small e, acute accent'
  '&ecirc;': 'ê', // 'small e, circumflex accent'
  '&euml;': 'ë', // 'small e, umlaut mark'
  '&igrave;': 'ì', // 'small i, grave accent'
  '&iacute;': 'í', // 'small i, acute accent'
  '&icirc;': 'î', // 'small i, circumflex accent'
  '&iuml;': 'ï', // 'small i, umlaut mark'
  '&eth;': 'ð', // 'small eth, Icelandic'
  '&ntilde;': 'ñ', // 'small n, tilde'
  '&ograve;': 'ò', // 'small o, grave accent'
  '&oacute;': 'ó', // 'small o, acute accent'
  '&ocirc;': 'ô', // 'small o, circumflex accent'
  '&otilde;': 'õ', // 'small o, tilde'
  '&ouml;': 'ö', // 'small o, umlaut mark'
  '&oslash;': 'ø', // 'small o, slash'
  '&ugrave;': 'ù', // 'small u, grave accent'
  '&uacute;': 'ú', // 'small u, acute accent'
  '&ucirc;': 'û', // 'small u, circumflex accent'
  '&uuml;': 'ü', // 'small u, umlaut mark'
  '&yacute;': 'ý', // 'small y, acute accent'
  '&thorn;': 'þ', // 'small thorn, Icelandic'
  '&yuml;': 'ÿ' // 'small y, umlaut mark'
}
